### PR TITLE
Adds extra fields to the speaker profile

### PR DESCRIPTION
**Pull request by chrisjrn**

### CODE REVIEW

**Comment by ghost** [comment]
Boolean fields should have a default (probably False), migrate complains. 
Also should accessibility/travel/accomodation with blank=True?

**Comment by chrisjrn** [comment]
On 17 June 2016 at 21:45, Scott Bragg notifications@github.com wrote:

> Boolean fields should have a default (probably False), migrate complains.
> Also should accessibility/travel/accomodation with blank=True?

Good points :)

> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/lca2017/symposion/pull/14#issuecomment-226921752, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAl-3Hua76pFa6H59_shAZhf_sYjLAZ3ks5qM3f-gaJpZM4I43Ki
> .

## 

--Christopher Neugebauer

Jabber: chrisjrn@gmail.com -- IRC: chrisjrn on irc.freenode.net -- WWW:
http://chrisjrn.com -- Twitter: @chrisjrn

**Comment by chrisjrn** [comment]
OK, try these.

**Comment by ghost** [comment]
Works for me (both new deployment and dev environment). New forms fields work too

**Pull request merged**
